# Copyright 2020 The Kubernetes Authors.
# SPDX-License-Identifier: Apache-2.0


# Prometheus Monitor Service (Metrics)
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    control-plane: controller-manager
  name: app-metrics-monitor
  namespace: system
spec:
  endpoints:
    - path: /metrics
      port: https
  selector:
    matchLabels:
      app.kubernetes.io/name: kube-app-manager
      control-plane: controller-manager